### ISSUE TITLE
Renaming adma_msgs to adma_ros_driver_msgs breaks compatibility with existing rosbags and depending packages

### ISSUE THREAD

**Issue by FranzAlbers** [GeneSysElektronik/adma_ros_driver#10]
Hello,

In commit 0c81996, the adma_msgs were renamed to adma_ros_driver_msgs. 
Unfortunately, this breaks compatibility with existing previously recorded Rosbags and with other (custom) packages that depend on these messages. Changes to the messages should be done only very rarely and carefully to keep compatibility.

We kindly ask you to revert this commit, as renaming these messages has no inherent benefit, and the previous naming was not uncommon in ROS (see, for example, https://github.com/ros-drivers/ros2_ouster_drivers).

**Comment by GeneSysTobiasWagner** [comment]
As discussed today, the renaming must be implemented.

Earlier recorded data that contain the data_recorded topic might be reprocessed with the new naming. 

Furthermore, we can create a dedicated branch or tag in the repository specifically for you. This will allow you to clone the repository on additional devices or share it with customers by using the old naming of the ADMA msgs. In this branch, you can add your own usage hints and descriptions for your project.
