### ISSUE TITLE
UNIX time stamp is not set correctly

### ISSUE THREAD

**Issue by JAP3TH** [GeneSysElektronik/adma_ros_driver#16]
Nice work having the possibility to use ADMA integrated in ROS2. However, you calculate your time in millisecond format which leads to an overflow, as far as I see.

The function is `void ADMADriver::parseData(std::array<char, 856> recv_buf)`

```
//offset between UNIX and GNSS (in ms)
  unsigned long offset_gps_unix = 315964800000;
  uint32_t week_to_msec = 604800000;
  unsigned long timestamp;
```

Since unsigned integers have 32 bits ranging until 4,294,967,295, using `unsigned long` is not sufficient if you like to work with milliseconds. I would suggest you to either switch formats to seconds (precision doesn't suffer) or extend the range to `unsigned long long`.

Thanks and greetings!

**Comment by rschilli-dev** [comment]
@JAP3TH Thanks for your feedback! We've updated it by extending the range since we still want to keep the calculation based on msec. This fix will be part if the upcoming release!
