### ISSUE TITLE
NavSatFix - Wrong height

### ISSUE THREAD

**Issue by GeneSysTobiasWagner** [GeneSysElektronik/adma_ros_driver#18]
The NavSatFix outputs the height (MSL) instead of WGS84-Ellipsoid (HAE) (see [code](https://github.com/GeneSysElektronik/adma_ros_driver/blob/ros2_master/adma_ros2_driver/src/parser/adma2ros_parser.cpp#L513) of ROS2 driver)
In the ROS topic NavSatFix the height is defined as Altitude [m] positive above the WGS84 ellipsoid.

**Comment by rschilli-dev** [comment]
done by 410ffe45a8e92742c03020fa6ef0fe7de83c5021 and 4ab69972db2d09d44e21313fd6fd2ca8052d7bd2 for both ROS versions
