### ISSUE TITLE
ROS1 | ROS2: Scaling issue INS_Lat_Abs / INS_Long_Abs in online data

### ISSUE THREAD

**Issue by GeneSysTobiasWagner** [GeneSysElektronik/adma_ros_driver#4]
The **INS_Lat_Abs** and **INS_Long_Abs** data channels seem to have a scaling issue when recorded online. In the replayed data, it works properly.

**Comment by rschilli-dev** [comment]
Should be fixed with the PR #3. If this is validated for both versions, this issue can be closed.

**Comment by GeneSysTobiasWagner** [comment]
Bug has been fixed and successfully tested in ROS1 and ROS2.
