### ISSUE TITLE
Standardized package naming

### ISSUE THREAD

**Issue by GeneSysTobiasWagner** [GeneSysElektronik/adma_ros_driver#8]
According to ROS standards, package names should align with the naming of the driver. In this case, a recommended package name could be "adma_ros_driver_msgs" to replace the "adma_msgs". This name effectively conveys the purpose of the package, which is to provide messages for the Adma ROS driver.

**Comment by rschilli-dev** [comment]
for ros2 its done with commit 0c81996aae2c4bba151a076d9a84827b595aac3d. As soon as it is tested, it can be integrated to ros1.

**Comment by GeneSysTobiasWagner** [comment]
Tested successfully.
